### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by twhy**
Hi Madam/Sir,

I just add some improvements to the course site. Please let me know how you think about it.

About showing the material duration, please fill in some actual duration data, so I can try to add it into the lecture pages.

### CODE REVIEW

**Comment by twhy** [comment]
The job is no long available on upwork. Has it been taken by someone else?

**Comment by skjohansen** [comment]
yes it have sorry about that...

**Comment by twhy** [comment]
Never mind.  You can use my code for free if you like it.

**Comment by skjohansen** [comment]
> 
> 
> Never mind. You can use my code for free if you like it.

Sorry about that!
Thanks for letting me use the code! We will see what will be the result on the on going process.

**Pull request closed without merging**
